sudo: required

services:
  - docker
  
language: node_js

node_js:
  - "node"
  
before_install:
  - npm install -g gulp
  - npm install

install:
  - gulp 
  
script:
  - ./tests/start_selenium.sh
  - gulp test:local
